function [fitresult, gof] = sigmoid_fit(xdata, proportion)
%CREATEFIT(XDATA,PROPORTION)
%  Create a fit.
%
%  Data for 'sigmoid' fit:
%      X Input : xdata
%      Y Output: proportion
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 27-Mar-2019 15:21:58


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( xdata, proportion );

% Set up fittype and options.
ft = fittype( '1 ./ (1 + exp(-k*(x-x0)))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.464887630911822 0.734585014050371];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'proportion vs. xdata', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel xdata
% ylabel proportion
% grid on


